apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tomcat8
  name: svc-tomcat8
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32000
  selector:
    app: tomcat8
  type: NodePort
status:
  loadBalancer: {}
